FROM openjdk:11

LABEL COMPANY="Publicis Sapient"
LABEL APPLICATION="Onboarding-Model Service"

COPY /target/onboarding-model-0.0.1-SNAPSHOT.jar onboarding-model.jar

# EXPOSE 9010

# ENTRYPOINT ["java", "-jar", "onboarding-model.jar"]